/** 滚动盈利信息；由 scripts/fetch_earnings.py 自动生成。 */
const ROLLING_EARNINGS_DATA = {
  "meta": {
    "version": "v1-rules",
    "status": "valid",
    "updatedAt": "2026-09-04T04:01:15",
    "macroPeriod": "2026年7月",
    "companyPeriod": "20260630",
    "recordCount": 18,
    "sourcePolicy": "official-first"
  },
  "records": [
    {
      "id": "macro-profit",
      "entityType": "macro",
      "metric": "规上工业企业利润",
      "latest": "45,820.6亿元",
      "change": "累计同比 +17.6%",
      "judgment": "增长减速",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04"
    },
    {
      "id": "macro-revenue",
      "entityType": "macro",
      "metric": "规上工业企业营业收入",
      "latest": "809,230.7亿元",
      "change": "累计同比 +6.5%",
      "judgment": "增长减速",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04"
    },
    {
      "id": "macro-margin",
      "entityType": "macro",
      "metric": "规上工业营业收入利润率",
      "latest": "5.66%",
      "change": "利润总额÷营业收入",
      "judgment": "盈利质量观察",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04"
    },
    {
      "id": "macro-inventory",
      "entityType": "macro",
      "metric": "规上工业产成品存货",
      "latest": "+10.8%",
      "change": "较上期 +1.3个百分点",
      "judgment": "增长减速",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04"
    },
    {
      "id": "macro-receivable",
      "entityType": "macro",
      "metric": "规上工业应收账款",
      "latest": "+8.5%",
      "change": "较上期 +0.4个百分点",
      "judgment": "增长减速",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04"
    },
    {
      "id": "macro-loss-ratio",
      "entityType": "macro",
      "metric": "规上工业亏损企业比例",
      "latest": "29.9%",
      "change": "153,365/512,105家",
      "judgment": "盈利广度观察",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04"
    },
    {
      "id": "industry-其他制造业",
      "entityType": "industry",
      "metric": "其他制造业利润",
      "latest": "+4.1%",
      "change": "较上期 +6.0个百分点",
      "judgment": "增速反转 · 连续改善",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04",
      "rawValue": 4.1,
      "previousValue": -1.9
    },
    {
      "id": "industry-专用设备制造业",
      "entityType": "industry",
      "metric": "专用设备制造业利润",
      "latest": "+0.8%",
      "change": "较上期 +0.9个百分点",
      "judgment": "增速反转 · 连续改善",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04",
      "rawValue": 0.8,
      "previousValue": -0.1
    },
    {
      "id": "industry-纺织服装-服饰业",
      "entityType": "industry",
      "metric": "纺织服装、服饰业利润",
      "latest": "-17.2%",
      "change": "较上期 +10.8个百分点",
      "judgment": "连续改善",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04",
      "rawValue": -17.2,
      "previousValue": -28.0
    },
    {
      "id": "industry-非金属矿采选业",
      "entityType": "industry",
      "metric": "非金属矿采选业利润",
      "latest": "-0.3%",
      "change": "较上期 -10.4个百分点",
      "judgment": "由增转降 · 增长减速",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04",
      "rawValue": -0.3,
      "previousValue": 10.1
    },
    {
      "id": "industry-黑色金属冶炼和压延加工业",
      "entityType": "industry",
      "metric": "黑色金属冶炼和压延加工业利润",
      "latest": "-51.2%",
      "change": "较上期 -26.2个百分点",
      "judgment": "增长减速",
      "period": "2026年7月",
      "publishedAt": null,
      "sourceName": "国家统计局",
      "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
      "sourceLevel": "A",
      "checkedAt": "2026-09-04",
      "rawValue": -51.2,
      "previousValue": -25.0
    },
    {
      "id": "company-601872",
      "entityType": "company",
      "metric": "招商轮船（601872）",
      "latest": "营收+56.2% / 净利+227.6%",
      "change": "净利润 69.60亿元",
      "judgment": "增长加速 · 现金流同步",
      "period": "20260630",
      "publishedAt": "2026-08-31",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/601872/AN202608301828734424.html",
      "sourceLevel": "A-",
      "industry": "航运港口",
      "rawValue": 6959500459.03,
      "previousValue": null,
      "details": {
        "营业收入": 196.51,
        "营收同比": 56.15,
        "净利润": 69.6,
        "净利润同比": 227.57,
        "每股经营现金流": 1.01,
        "毛利率": 44.98,
        "扣非每股收益": 0.86,
        "公告标题": "招商轮船:招商轮船2026年半年度报告"
      }
    },
    {
      "id": "company-688825",
      "entityType": "company",
      "metric": "长鑫科技（688825）",
      "latest": "营收+873.6% / 净利+3427.8%",
      "change": "净利润 776.05亿元",
      "judgment": "低基数高增 · 现金流同步",
      "period": "20260630",
      "publishedAt": "2026-08-29",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/688825/AN202608281828635976.html",
      "sourceLevel": "A-",
      "industry": "半导体",
      "rawValue": 77605227520.0,
      "previousValue": null,
      "details": {
        "营业收入": 1503.1,
        "营收同比": 873.64,
        "净利润": 776.05,
        "净利润同比": 3427.76,
        "每股经营现金流": 2.18,
        "毛利率": 84.74,
        "扣非每股收益": 1.31,
        "公告标题": "长鑫科技:2026年半年度报告"
      }
    },
    {
      "id": "company-002460",
      "entityType": "company",
      "metric": "赣锋锂业（002460）",
      "latest": "营收+175.7% / 净利+901.4%",
      "change": "净利润 42.57亿元",
      "judgment": "低基数高增 · 现金流同步",
      "period": "20260630",
      "publishedAt": "2026-08-29",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/002460/AN202608280006758316.html",
      "sourceLevel": "A-",
      "industry": "能源金属",
      "rawValue": 4257164842.1,
      "previousValue": null,
      "details": {
        "营业收入": 230.97,
        "营收同比": 175.75,
        "净利润": 42.57,
        "净利润同比": 901.36,
        "每股经营现金流": 0.63,
        "毛利率": 31.51,
        "扣非每股收益": 1.84,
        "公告标题": "赣锋锂业:2026年半年度报告"
      }
    },
    {
      "id": "company-000426",
      "entityType": "company",
      "metric": "兴业银锡（000426）",
      "latest": "营收+73.1% / 净利+184.4%",
      "change": "净利润 22.63亿元",
      "judgment": "增长加速 · 现金流同步",
      "period": "20260630",
      "publishedAt": "2026-08-29",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/000426/AN202608280006758325.html",
      "sourceLevel": "A-",
      "industry": "贵金属",
      "rawValue": 2263056168.41,
      "previousValue": null,
      "details": {
        "营业收入": 42.82,
        "营收同比": 73.13,
        "净利润": 22.63,
        "净利润同比": 184.42,
        "每股经营现金流": 1.19,
        "毛利率": 68.75,
        "扣非每股收益": 1.02,
        "公告标题": "兴业银锡:2026年半年度报告"
      }
    },
    {
      "id": "company-688221",
      "entityType": "company",
      "metric": "前沿生物（688221）",
      "latest": "营收+434.3% / 净利+253.0%",
      "change": "净利润 1.49亿元",
      "judgment": "增长加速 · 现金流同步",
      "period": "20260630",
      "publishedAt": "2026-08-31",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/688221/AN202608301828734243.html",
      "sourceLevel": "A-",
      "industry": "化学制药",
      "rawValue": 148929627.03,
      "previousValue": null,
      "details": {
        "营业收入": 3.13,
        "营收同比": 434.27,
        "净利润": 1.49,
        "净利润同比": 252.98,
        "每股经营现金流": 0.48,
        "毛利率": 84.05,
        "扣非每股收益": 0.34,
        "公告标题": "前沿生物:前沿生物2026年半年度报告"
      }
    },
    {
      "id": "company-603567",
      "entityType": "company",
      "metric": "珍宝岛（603567）",
      "latest": "营收-58.6% / 净利-246.1%",
      "change": "净利润 -2.71亿元",
      "judgment": "增长减速",
      "period": "20260630",
      "publishedAt": "2026-08-29",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/603567/AN202608281828647556.html",
      "sourceLevel": "A-",
      "industry": "中药Ⅱ",
      "rawValue": -270974735.96,
      "previousValue": null,
      "details": {
        "营业收入": 2.96,
        "营收同比": -58.6,
        "净利润": -2.71,
        "净利润同比": -246.12,
        "每股经营现金流": 0.11,
        "毛利率": 5.53,
        "扣非每股收益": -0.29,
        "公告标题": "珍宝岛:黑龙江珍宝岛药业股份有限公司2026年半年度报告"
      }
    },
    {
      "id": "company-600325",
      "entityType": "company",
      "metric": "华发股份（600325）",
      "latest": "营收-50.2% / 净利-2225.7%",
      "change": "净利润 -36.54亿元",
      "judgment": "盈利明显承压",
      "period": "20260630",
      "publishedAt": "2026-08-31",
      "sourceName": "交易所公告镜像索引",
      "sourceUrl": "https://data.eastmoney.com/notices/detail/600325/AN202608301828733871.html",
      "sourceLevel": "A-",
      "industry": "房地产开发",
      "rawValue": -3654293135.73,
      "previousValue": null,
      "details": {
        "营业收入": 190.29,
        "营收同比": -50.18,
        "净利润": -36.54,
        "净利润同比": -2225.71,
        "每股经营现金流": -0.31,
        "毛利率": 5.33,
        "扣非每股收益": -1.35,
        "公告标题": "华发股份:华发股份2026年半年度报告"
      }
    }
  ],
  "history": [
    {
      "date": "2026-08-10",
      "macroPeriod": "2026年6月",
      "companyPeriod": "20260630",
      "recordIds": [
        "macro-profit",
        "macro-revenue",
        "macro-margin",
        "macro-inventory",
        "macro-receivable",
        "macro-loss-ratio",
        "industry-水的生产和供应业",
        "industry-医药制造业",
        "industry-通用设备制造业",
        "industry-化学纤维制造业",
        "industry-开采专业及辅助性活动",
        "company-300503",
        "company-001339",
        "company-300184",
        "company-688266",
        "company-000933",
        "company-603727",
        "company-002828"
      ]
    },
    {
      "archivedAt": "2026-08-11T09:40:07",
      "macroPeriod": "2026年6月",
      "companyPeriod": "20260630",
      "records": [
        {
          "id": "macro-profit",
          "entityType": "macro",
          "metric": "规上工业企业利润",
          "latest": "39,479.9亿元",
          "change": "累计同比 +18.7%",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10"
        },
        {
          "id": "macro-revenue",
          "entityType": "macro",
          "metric": "规上工业企业营业收入",
          "latest": "692,614.2亿元",
          "change": "累计同比 +6.5%",
          "judgment": "连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10"
        },
        {
          "id": "macro-margin",
          "entityType": "macro",
          "metric": "规上工业营业收入利润率",
          "latest": "5.70%",
          "change": "利润总额÷营业收入",
          "judgment": "盈利质量观察",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10"
        },
        {
          "id": "macro-inventory",
          "entityType": "macro",
          "metric": "规上工业产成品存货",
          "latest": "+9.5%",
          "change": "较上期 +0.7个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10"
        },
        {
          "id": "macro-receivable",
          "entityType": "macro",
          "metric": "规上工业应收账款",
          "latest": "+8.1%",
          "change": "较上期 +0.4个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10"
        },
        {
          "id": "macro-loss-ratio",
          "entityType": "macro",
          "metric": "规上工业亏损企业比例",
          "latest": "31.1%",
          "change": "158,961/511,702家",
          "judgment": "盈利广度观察",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10"
        },
        {
          "id": "industry-水的生产和供应业",
          "entityType": "industry",
          "metric": "水的生产和供应业利润",
          "latest": "+4.2%",
          "change": "较上期 +6.6个百分点",
          "judgment": "增速反转 · 连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10",
          "rawValue": 4.2,
          "previousValue": -2.4
        },
        {
          "id": "industry-医药制造业",
          "entityType": "industry",
          "metric": "医药制造业利润",
          "latest": "+4.2%",
          "change": "较上期 +5.5个百分点",
          "judgment": "增速反转 · 连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10",
          "rawValue": 4.2,
          "previousValue": -1.3
        },
        {
          "id": "industry-通用设备制造业",
          "entityType": "industry",
          "metric": "通用设备制造业利润",
          "latest": "+1.5%",
          "change": "较上期 +1.7个百分点",
          "judgment": "增速反转 · 连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10",
          "rawValue": 1.5,
          "previousValue": -0.2
        },
        {
          "id": "industry-化学纤维制造业",
          "entityType": "industry",
          "metric": "化学纤维制造业利润",
          "latest": "+102.0%",
          "change": "较上期 -34.9个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10",
          "rawValue": 102.0,
          "previousValue": 136.9
        },
        {
          "id": "industry-开采专业及辅助性活动",
          "entityType": "industry",
          "metric": "开采专业及辅助性活动利润",
          "latest": "+136.0%",
          "change": "较上期 -26.6个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-10",
          "rawValue": 136.0,
          "previousValue": 162.6
        },
        {
          "id": "company-300503",
          "entityType": "company",
          "metric": "昊志机电（300503）",
          "latest": "营收+65.9% / 净利+266.6%",
          "change": "净利润 2.32亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-07-21",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/300503/AN202607201827147124.html",
          "sourceLevel": "A-",
          "industry": "通用设备",
          "rawValue": 232342843.01,
          "previousValue": null,
          "details": {
            "营业收入": 11.66,
            "营收同比": 65.86,
            "净利润": 2.32,
            "净利润同比": 266.57,
            "每股经营现金流": 0.17,
            "毛利率": 42.45,
            "扣非每股收益": 0.7,
            "公告标题": "昊志机电:2026年半年度报告"
          }
        },
        {
          "id": "company-001339",
          "entityType": "company",
          "metric": "智微智能（001339）",
          "latest": "营收+56.6% / 净利+281.9%",
          "change": "净利润 3.88亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-07-18",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/001339/AN202607171827061996.html",
          "sourceLevel": "A-",
          "industry": "计算机设备",
          "rawValue": 388460769.92,
          "previousValue": null,
          "details": {
            "营业收入": 30.5,
            "营收同比": 56.64,
            "净利润": 3.88,
            "净利润同比": 281.92,
            "每股经营现金流": 2.95,
            "毛利率": 39.52,
            "扣非每股收益": 1.14,
            "公告标题": "智微智能:2026年半年度报告"
          }
        },
        {
          "id": "company-300184",
          "entityType": "company",
          "metric": "力源信息（300184）",
          "latest": "营收+59.5% / 净利+209.5%",
          "change": "净利润 2.98亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-08-10",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/300184/AN202608091827791313.html",
          "sourceLevel": "A-",
          "industry": "其他电子Ⅱ",
          "rawValue": 297519061.1,
          "previousValue": null,
          "details": {
            "营业收入": 64.32,
            "营收同比": 59.46,
            "净利润": 2.98,
            "净利润同比": 209.5,
            "每股经营现金流": 0.09,
            "毛利率": 10.35,
            "扣非每股收益": 0.26,
            "公告标题": "力源信息:2026年半年度报告"
          }
        },
        {
          "id": "company-688266",
          "entityType": "company",
          "metric": "泽璟制药（688266）",
          "latest": "营收+220.9% / 净利+979.1%",
          "change": "净利润 6.40亿元",
          "judgment": "低基数高增 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-08-01",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/688266/AN202607311827531291.html",
          "sourceLevel": "A-",
          "industry": "化学制药",
          "rawValue": 640011104.13,
          "previousValue": null,
          "details": {
            "营业收入": 12.05,
            "营收同比": 220.88,
            "净利润": 6.4,
            "净利润同比": 979.09,
            "每股经营现金流": 3.05,
            "毛利率": 94.64,
            "扣非每股收益": 2.33,
            "公告标题": "泽璟制药:泽璟制药2026年半年度报告"
          }
        },
        {
          "id": "company-000933",
          "entityType": "company",
          "metric": "神火股份（000933）",
          "latest": "营收+21.4% / 净利+151.1%",
          "change": "净利润 47.81亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-07-28",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/000933/AN202607271827384787.html",
          "sourceLevel": "A-",
          "industry": "工业金属",
          "rawValue": 4781377305.4,
          "previousValue": null,
          "details": {
            "营业收入": 247.91,
            "营收同比": 21.35,
            "净利润": 47.81,
            "净利润同比": 151.06,
            "每股经营现金流": 3.2,
            "毛利率": 36.17,
            "扣非每股收益": 2.16,
            "公告标题": "神火股份:2026年半年度报告"
          }
        },
        {
          "id": "company-603727",
          "entityType": "company",
          "metric": "博迈科（603727）",
          "latest": "营收-26.7% / 净利-668.7%",
          "change": "净利润 -0.70亿元",
          "judgment": "盈利明显承压",
          "period": "20260630",
          "publishedAt": "2026-07-25",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/603727/AN202607241827318954.html",
          "sourceLevel": "A-",
          "industry": "油服工程",
          "rawValue": -70440288.38,
          "previousValue": null,
          "details": {
            "营业收入": 7.64,
            "营收同比": -26.72,
            "净利润": -0.7,
            "净利润同比": -668.72,
            "每股经营现金流": 0.94,
            "毛利率": 5.8,
            "扣非每股收益": -0.28,
            "公告标题": "博迈科:博迈科海洋工程股份有限公司2026年半年度报告"
          }
        },
        {
          "id": "company-002828",
          "entityType": "company",
          "metric": "贝肯能源（002828）",
          "latest": "营收-32.4% / 净利-999.5%",
          "change": "净利润 -1.24亿元",
          "judgment": "盈利明显承压",
          "period": "20260630",
          "publishedAt": "2026-08-08",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/002828/AN202608071827750510.html",
          "sourceLevel": "A-",
          "industry": "油服工程",
          "rawValue": -124316612.8,
          "previousValue": null,
          "details": {
            "营业收入": 3.14,
            "营收同比": -32.41,
            "净利润": -1.24,
            "净利润同比": -999.48,
            "每股经营现金流": -0.04,
            "毛利率": 0.46,
            "扣非每股收益": -0.44,
            "公告标题": "贝肯能源:2026年半年度报告"
          }
        }
      ]
    },
    {
      "archivedAt": "2026-09-04T04:01:15",
      "macroPeriod": "2026年6月",
      "companyPeriod": "20260630",
      "records": [
        {
          "id": "macro-profit",
          "entityType": "macro",
          "metric": "规上工业企业利润",
          "latest": "39,479.9亿元",
          "change": "累计同比 +18.7%",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11"
        },
        {
          "id": "macro-revenue",
          "entityType": "macro",
          "metric": "规上工业企业营业收入",
          "latest": "692,614.2亿元",
          "change": "累计同比 +6.5%",
          "judgment": "连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11"
        },
        {
          "id": "macro-margin",
          "entityType": "macro",
          "metric": "规上工业营业收入利润率",
          "latest": "5.70%",
          "change": "利润总额÷营业收入",
          "judgment": "盈利质量观察",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11"
        },
        {
          "id": "macro-inventory",
          "entityType": "macro",
          "metric": "规上工业产成品存货",
          "latest": "+9.5%",
          "change": "较上期 +0.7个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11"
        },
        {
          "id": "macro-receivable",
          "entityType": "macro",
          "metric": "规上工业应收账款",
          "latest": "+8.1%",
          "change": "较上期 +0.4个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11"
        },
        {
          "id": "macro-loss-ratio",
          "entityType": "macro",
          "metric": "规上工业亏损企业比例",
          "latest": "31.1%",
          "change": "158,961/511,702家",
          "judgment": "盈利广度观察",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11"
        },
        {
          "id": "industry-水的生产和供应业",
          "entityType": "industry",
          "metric": "水的生产和供应业利润",
          "latest": "+4.2%",
          "change": "较上期 +6.6个百分点",
          "judgment": "增速反转 · 连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11",
          "rawValue": 4.2,
          "previousValue": -2.4
        },
        {
          "id": "industry-医药制造业",
          "entityType": "industry",
          "metric": "医药制造业利润",
          "latest": "+4.2%",
          "change": "较上期 +5.5个百分点",
          "judgment": "增速反转 · 连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11",
          "rawValue": 4.2,
          "previousValue": -1.3
        },
        {
          "id": "industry-通用设备制造业",
          "entityType": "industry",
          "metric": "通用设备制造业利润",
          "latest": "+1.5%",
          "change": "较上期 +1.7个百分点",
          "judgment": "增速反转 · 连续改善",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11",
          "rawValue": 1.5,
          "previousValue": -0.2
        },
        {
          "id": "industry-化学纤维制造业",
          "entityType": "industry",
          "metric": "化学纤维制造业利润",
          "latest": "+102.0%",
          "change": "较上期 -34.9个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11",
          "rawValue": 102.0,
          "previousValue": 136.9
        },
        {
          "id": "industry-开采专业及辅助性活动",
          "entityType": "industry",
          "metric": "开采专业及辅助性活动利润",
          "latest": "+136.0%",
          "change": "较上期 -26.6个百分点",
          "judgment": "增长减速",
          "period": "2026年6月",
          "publishedAt": null,
          "sourceName": "国家统计局",
          "sourceUrl": "https://data.stats.gov.cn/dg/website/page.html",
          "sourceLevel": "A",
          "checkedAt": "2026-08-11",
          "rawValue": 136.0,
          "previousValue": 162.6
        },
        {
          "id": "company-301308",
          "entityType": "company",
          "metric": "江波龙（301308）",
          "latest": "营收+136.3% / 净利+71528.7%",
          "change": "净利润 105.77亿元",
          "judgment": "低基数高增 · 现金流未验证",
          "period": "20260630",
          "publishedAt": "2026-08-11",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/301308/AN202608101827817080.html",
          "sourceLevel": "A-",
          "industry": "半导体",
          "rawValue": 10576875808.95,
          "previousValue": null,
          "details": {
            "营业收入": 240.88,
            "营收同比": 136.26,
            "净利润": 105.77,
            "净利润同比": 71528.66,
            "每股经营现金流": -7.45,
            "毛利率": 58.9,
            "扣非每股收益": 23.93,
            "公告标题": "江波龙:2026年半年度报告"
          }
        },
        {
          "id": "company-300503",
          "entityType": "company",
          "metric": "昊志机电（300503）",
          "latest": "营收+65.9% / 净利+266.6%",
          "change": "净利润 2.32亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-07-21",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/300503/AN202607201827147124.html",
          "sourceLevel": "A-",
          "industry": "通用设备",
          "rawValue": 232342843.01,
          "previousValue": null,
          "details": {
            "营业收入": 11.66,
            "营收同比": 65.86,
            "净利润": 2.32,
            "净利润同比": 266.57,
            "每股经营现金流": 0.17,
            "毛利率": 42.45,
            "扣非每股收益": 0.7,
            "公告标题": "昊志机电:2026年半年度报告"
          }
        },
        {
          "id": "company-001339",
          "entityType": "company",
          "metric": "智微智能（001339）",
          "latest": "营收+56.6% / 净利+281.9%",
          "change": "净利润 3.88亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-07-18",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/001339/AN202607171827061996.html",
          "sourceLevel": "A-",
          "industry": "计算机设备",
          "rawValue": 388460769.92,
          "previousValue": null,
          "details": {
            "营业收入": 30.5,
            "营收同比": 56.64,
            "净利润": 3.88,
            "净利润同比": 281.92,
            "每股经营现金流": 2.95,
            "毛利率": 39.52,
            "扣非每股收益": 1.14,
            "公告标题": "智微智能:2026年半年度报告"
          }
        },
        {
          "id": "company-300184",
          "entityType": "company",
          "metric": "力源信息（300184）",
          "latest": "营收+59.5% / 净利+209.5%",
          "change": "净利润 2.98亿元",
          "judgment": "增长加速 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-08-10",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/300184/AN202608091827791313.html",
          "sourceLevel": "A-",
          "industry": "其他电子Ⅱ",
          "rawValue": 297519061.1,
          "previousValue": null,
          "details": {
            "营业收入": 64.32,
            "营收同比": 59.46,
            "净利润": 2.98,
            "净利润同比": 209.5,
            "每股经营现金流": 0.09,
            "毛利率": 10.35,
            "扣非每股收益": 0.26,
            "公告标题": "力源信息:2026年半年度报告"
          }
        },
        {
          "id": "company-688266",
          "entityType": "company",
          "metric": "泽璟制药（688266）",
          "latest": "营收+220.9% / 净利+979.1%",
          "change": "净利润 6.40亿元",
          "judgment": "低基数高增 · 现金流同步",
          "period": "20260630",
          "publishedAt": "2026-08-01",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/688266/AN202607311827531291.html",
          "sourceLevel": "A-",
          "industry": "化学制药",
          "rawValue": 640011104.13,
          "previousValue": null,
          "details": {
            "营业收入": 12.05,
            "营收同比": 220.88,
            "净利润": 6.4,
            "净利润同比": 979.09,
            "每股经营现金流": 3.05,
            "毛利率": 94.64,
            "扣非每股收益": 2.33,
            "公告标题": "泽璟制药:泽璟制药2026年半年度报告"
          }
        },
        {
          "id": "company-603727",
          "entityType": "company",
          "metric": "博迈科（603727）",
          "latest": "营收-26.7% / 净利-668.7%",
          "change": "净利润 -0.70亿元",
          "judgment": "盈利明显承压",
          "period": "20260630",
          "publishedAt": "2026-07-25",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/603727/AN202607241827318954.html",
          "sourceLevel": "A-",
          "industry": "油服工程",
          "rawValue": -70440288.38,
          "previousValue": null,
          "details": {
            "营业收入": 7.64,
            "营收同比": -26.72,
            "净利润": -0.7,
            "净利润同比": -668.72,
            "每股经营现金流": 0.94,
            "毛利率": 5.8,
            "扣非每股收益": -0.28,
            "公告标题": "博迈科:博迈科海洋工程股份有限公司2026年半年度报告"
          }
        },
        {
          "id": "company-002828",
          "entityType": "company",
          "metric": "贝肯能源（002828）",
          "latest": "营收-32.4% / 净利-999.5%",
          "change": "净利润 -1.24亿元",
          "judgment": "盈利明显承压",
          "period": "20260630",
          "publishedAt": "2026-08-08",
          "sourceName": "交易所公告镜像索引",
          "sourceUrl": "https://data.eastmoney.com/notices/detail/002828/AN202608071827750510.html",
          "sourceLevel": "A-",
          "industry": "油服工程",
          "rawValue": -124316612.8,
          "previousValue": null,
          "details": {
            "营业收入": 3.14,
            "营收同比": -32.41,
            "净利润": -1.24,
            "净利润同比": -999.48,
            "每股经营现金流": -0.04,
            "毛利率": 0.46,
            "扣非每股收益": -0.44,
            "公告标题": "贝肯能源:2026年半年度报告"
          }
        }
      ]
    }
  ]
};
